### ISSUE TITLE
Where is "disambiguator_evaluation.py"?

### ISSUE THREAD

**Issue by Xiao-wen-Sun** [JChiyah/exploring-mm-in-simmc2#1]

**Comment by JChiyah** [comment]
Hi, this file is in the SIMMC2.0 repository: `simmc2/model/utils/disambiguator_evaluation.py`. I have also uploaded it now to the repository: https://github.com/JChiyah/exploring-mm-in-simmc2/commit/babc0320eaf3675f7dd147ec292297e7c83d19d8
